notifiers:

  pushover:
    enabled: false
    user: 
    token: 

  telegram:
    enabled: false
    chat_id:
    token:

  twilio:
    enabled: false
    accountSid: 
    notif_number: 
    authToken: 
    senderNumber: 

ignore:

token:
